"""initial modular layout for tlink

Revision ID: a38cf3f049a6
Revises: 
Create Date: 2026-06-13 17:14:46.127691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a38cf3f049a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mes_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wms_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wms_materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('erp_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'AWAITING_MATERIALS', 'IN_PRODUCTION', 'READY', 'SHIPPED', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['mes_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mes_product_recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_per_unit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['wms_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['mes_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'material_id', name='uq_product_material_mes')
    )
    op.create_table('mes_production_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('quantity_molded', sa.Integer(), nullable=False),
    sa.Column('quantity_good', sa.Integer(), nullable=False),
    sa.Column('quantity_defective', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('MOLDING', 'CURING', 'MATURING', 'DONE', name='batchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('operator_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['wms_locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['mes_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wms_material_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('INFLOW', 'OUTFLOW', name='transactiontype'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['wms_locations.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['wms_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wms_material_transactions')
    op.drop_table('mes_production_batches')
    op.drop_table('mes_product_recipes')
    op.drop_table('erp_orders')
    op.drop_table('wms_materials')
    op.drop_table('wms_locations')
    op.drop_table('mes_products')
    # ### end Alembic commands ###
