"""add finished goods inventory and waybills

Revision ID: b5bfc88a68ff
Revises: a38cf3f049a6
Create Date: 2026-06-13 21:00:25.591432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5bfc88a68ff'
down_revision: Union[str, Sequence[str], None] = 'a38cf3f049a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_finished_goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['mes_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('erp_waybills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=100), nullable=False),
    sa.Column('truck_number', sa.String(length=20), nullable=False),
    sa.Column('quantity_shipped', sa.Integer(), nullable=False),
    sa.Column('shipped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['erp_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('erp_waybills')
    op.drop_table('erp_finished_goods')
    # ### end Alembic commands ###
